# Image for jvm
# copy the jar file in container
# command to execute
FROM openjdk:22-jdk 
ADD target/springdemo.jar springdemo.jar
ENTRYPOINT [ "java", "-jar", "/springdemo.jar" ]

# -t=tag .=same directory or give address
# to run docker build -t devspring/springdemo:v1 .

