version: "3.7"

services:
  app:
    build:
    ports:
    - "8080:8080"
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Ankit
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devspring
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
    - postgres-d-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres-d-data